[build]
  functions = "netlify/functions"
  publish = "."
  environment = { NODE_VERSION = "18" }

[functions]
  node_bundler = "esbuild"

# Optional: increase function timeout if your DB queries take longer
[functions."*"]
  timeout = 20

# Redirect /admin to /admin.html
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
  force = true

# Ensure clean URLs (optional but good for SEO)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
